# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
version: "3.9"

services:
  github-runner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: github-runner
    restart: always
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./_work:/home/runner/_work
    networks:
      - runner-net

networks:
  runner-net:
    driver: bridge

