name: Deploy Hospital App with Nomad and Octopus

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ENVIRONMENT: dev
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      KEY_NAME: ${{ secrets.KEY_NAME }}
      PUBLIC_KEY_PATH: ${{ secrets.PUBLIC_KEY_PATH }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: latest

      - name: Generate dev.tfvars
        run: |
          mkdir -p environment
          cat <<EOF > environment/dev.tfvars
          environment           = "${ENVIRONMENT}"
          aws_region            = "${AWS_REGION}"
          vpc_cidrblock         = "10.0.0.0/16"
          countsub              = 2
          create_subnet         = true
          create_elastic_ip     = true
          key_name              = "${KEY_NAME}"
          public_key_path       = "${PUBLIC_KEY_PATH}"
          db_password           = "${DB_PASSWORD}"
          db_username           = "mysql"
          db_name               = "devdb"
          db_instance_class     = "db.t3.micro"
          db_allocated_storage  = 20
          nomad_ami_id          = "ami-083ac04a8442d4b7f"
          nomad_instance_type   = "t3.small"
          nomad_server_count    = 3
          nomad_client_ami_id   = "ami-083ac04a8442d4b7f"
          nomad_client_instance_type = "t3.micro"
          nomad_client_desired_capacity = 1
          nomad_client_max_size = 2
          nomad_client_min_size = 1
          nomad_address         = "http://placeholder.nomad.local"
          vault_ami_id          = "ami-083ac04a8442d4b7f"
          vault_instance_type   = "t3.micro"
          consul_ami_id         = "ami-083ac04a8442d4b7f"
          consul_instance_type  = "t3.micro"
          EOF

      - name: OpenTofu Init
        run: tofu init

      - name: OpenTofu Plan
        run: tofu plan -var-file="environment/dev.tfvars"

      - name: Deploy with OpenTofu
        run: tofu apply -var-file="environment/dev.tfvars" -auto-approve
